In [37]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score,mean_squared_error

In [39]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score,confusion_matrix,classification_report

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    str    
 4   Sex          891 non-null    str    
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    str    
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str    
 11  Embarked     889 non-null    str    
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB


In [42]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [43]:
df['Age']= df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    str    
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    str    
dtypes: float64(2), int64(4), str(2)
memory usage: 60.8 KB


In [45]:
df = pd.get_dummies(df,columns=['Sex','Embarked'],drop_first=True)

In [46]:
x = df[['Age']]
y=df['Fare']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = LinearRegression()
model.fit(x_train,y_train)
pre = model.predict(x_test)

print("R2 Score: ",r2_score(y_test,pre))
print('MSE: ',mean_squared_error(y_test,pre))

R2 Score:  0.0146037912223973
MSE:  1524.8312803377087


In [47]:
x = df[["Pclass","Age","SibSp","Parch","Sex_male"]]
y = df['Fare']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = LinearRegression()
model.fit(x_train,y_train)
pre = model.predict(x_test)

print("R2 Score: ",r2_score(y_test,pre))
print('MSE: ',mean_squared_error(y_test,pre))

R2 Score:  0.39489278976425124
MSE:  936.3608200502017


In [48]:
x = df.drop(['Fare'],axis=1)
y = df['Fare']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
poly = PolynomialFeatures(degree=3)
x_train = poly.fit_transform(x_train)
x_test = poly.transform(x_test)

model = LinearRegression()
model.fit(x_train,y_train)
pre = model.predict(x_test)

print("R2 Score: ",r2_score(y_test,pre))
print('MSE: ',mean_squared_error(y_test,pre))

R2 Score:  -0.8392365622357207
MSE:  2846.089133544436


In [49]:
x = df.drop(['Survived'],axis=1)
y = df['Survived']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)
pre = model.predict(x_test)

print(accuracy_score(y_test,pre))
print(precision_score(y_test,pre))
print(recall_score(y_test,pre))
print(f1_score(y_test,pre))
print(confusion_matrix(y_test,pre))


0.7039106145251397
0.6779661016949152
0.5405405405405406
0.6015037593984962
[[86 19]
 [34 40]]


In [ ]:
x = df.drop(['Survived'],axis=1)
y = df['Survived']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = DecisionTreeClassifier(criterion='entropy',max_depth=3,random_state=42)
model.fit(x_train,y_train)
pre = model.predict(x_test)

print(accuracy_score(y_test,pre))
print(precision_score(y_test,pre))
print(recall_score(y_test,pre))
print(f1_score(y_test,pre))
print(confusion_matrix(y_test,pre))


0.7988826815642458
0.796875
0.6891891891891891
0.7391304347826086
[[92 13]
 [23 51]]


In [51]:
x = df.drop(['Survived'],axis=1)
y = df['Survived']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = RandomForestClassifier(n_estimators=100,max_depth=4)
model.fit(x_train,y_train)
pre = model.predict(x_test)

print(accuracy_score(y_test,pre))
print(precision_score(y_test,pre))
print(recall_score(y_test,pre))
print(f1_score(y_test,pre))
print(confusion_matrix(y_test,pre))


0.8100558659217877
0.8225806451612904
0.6891891891891891
0.75
[[94 11]
 [23 51]]


In [52]:
x = df.drop(['Survived'],axis=1)
y = df['Survived']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = SVC(C=10,kernel='rbf')
model.fit(x_train,y_train)
pre = model.predict(x_test)

print(accuracy_score(y_test,pre))
print(precision_score(y_test,pre))
print(recall_score(y_test,pre))
print(f1_score(y_test,pre))
print(confusion_matrix(y_test,pre))


0.7206703910614525
0.8157894736842105
0.4189189189189189
0.5535714285714286
[[98  7]
 [43 31]]
